updated request arm access API
CBIIT/bento-users pull request #22
Opened 2022-07-20 21:09 UTC by knockknockyoo

1. optional firstname, lastname, and organization in given parameters
2. fixed; optional organization is not stored
3. deleted reviewAdminName, armID and userID in Access Object
4. deleted empty reviewDate, comment

2022-07-20 21:19 UTC, knockknockyoo reviewed
updated request-arm-access API

2022-07-20 21:19 UTC, knockknockyoo commented on data-management/neo4j-service.js
> +        WHERE user.email='${user.getEmail()}' and user.IDP ='${user.getIDP()}' and req.accessStatus in ['${REQUESTED}', '${APPROVED}']
if a user requests 'requested' or 'approved' as an access-arm status again, it will throw an error.

2022-07-20 21:19 UTC, knockknockyoo commented on data-management/data-interface.js
> +        if (!p.userInfo.armIDs) throw new Error(errorName.MISSING_ARM_REQUEST_INPUTS)
optional first-name, last-name, and organization

2022-07-20 21:19 UTC, knockknockyoo commented on model/arm-access.js
> +    }
reviewAdminName, armID and userID should not store in ArmAccess object

2022-07-20 21:19 UTC, knockknockyoo commented on data-management/neo4j-service.js
> +            })-[:of_arm]->(arm)
reviewDate and comment are not stored in Access.

2022-07-20 22:43 UTC, n2iw requested changes
All good, except please make sure only one **Access** per arm per user.

2022-07-21 15:03 UTC, knockknockyoo reviewed
applied the changes. Thank you.

2022-07-21 15:03 UTC, knockknockyoo commented on data-management/neo4j-service.js
> +            MERGE (user)<-[:of_user]-(access:Access)-[:of_arm]->(arm)
A user is not allowed to create multiple Accesses per Arm.

2022-07-21 15:57 UTC, n2iw approved these changes

2022-07-21 15:57 UTC, merged