Store UserInfo Into Session
CBIIT/bento-users pull request #30
Opened 2022-07-27 21:03 UTC by knockknockyoo

Store userInfo in session
- role
- organization
- status

2022-07-27 22:10 UTC, n2iw requested changes
ACL should only contain "approved" arms.

2022-07-28 16:49 UTC, knockknockyoo reviewed
updated.

2022-07-28 16:49 UTC, knockknockyoo commented on services/arm-access.js
> +            if (isCaseInsensitiveEqual(armAccess.getAccessStatus(), APPROVED)) {
only APPROVED access status will be stored in the user-session

2022-08-02 19:43 UTC, n2iw approved these changes

2022-08-02 19:43 UTC, merged