Auto save a new authenticated user
CBIIT/bento-users pull request #9
Opened 2022-07-12 18:39 UTC by knockknockyoo

BENTO-1897

1. Created an user model
2. Stored a user if not existed in the database
3. Added an utility to verify an element in the array
4. Added test codes

2022-07-13 21:46 UTC, n2iw requested changes
When saving a new user, system shouldn't try to  send emails to admin or the user. Please test with an empty Neo4j, and make sure after login and calling getMyUser, a new user recorded is created in Neo4j.

2022-07-14 14:27 UTC, knockknockyoo reviewed
fixed not to send an email notification after auto-generated user registration

2022-07-14 14:27 UTC, knockknockyoo commented on data-management/data-interface.js
> +        const notify = (parameters.isNotify === false) ? parameters.isNotify: true;
fixed not to send an email notification after auto-generated user registration

2022-07-14 16:27 UTC, n2iw requested changes
1. Please make new user have role of "non-member", and status of ""
2. Please don't set editDate for a new user.
3. Please rename user's "status" to "userStatus"

2022-07-14 16:44 UTC, knockknockyoo reviewed
1. for member "non-member", and status of ""
2. editDate for a new user.
3. update "status" to "userStatus" field and graphql schema

2022-07-14 16:44 UTC, knockknockyoo commented on data-management/neo4j-service.js
> +            editDate: '',
new user does not set edit date

2022-07-14 16:44 UTC, knockknockyoo commented on graphql/schema.graphql
> +    userStatus: String
userstatus field changed

2022-07-14 16:44 UTC, knockknockyoo commented on data-management/neo4j-service.js
> +            userStatus: $status,
userstatus field changed

2022-07-14 18:01 UTC, knockknockyoo reviewed
fixed the changes
1. user-role
2. user-status

2022-07-14 18:01 UTC, knockknockyoo commented on data-management/data-interface.js
> +            status: NONE,
a new register user assigned as NONE of user-status as empty string ""

2022-07-14 19:30 UTC, knockknockyoo reviewed
added inactive & active

2022-07-14 19:30 UTC, knockknockyoo commented on constants/user-constant.js
> +    INACTIVE: 'inactive',
added inactive

2022-07-14 19:38 UTC, n2iw approved these changes

2022-07-14 19:39 UTC, merged